/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residents;

import config.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import models.DocumentItem;


public class requestDocument extends javax.swing.JFrame {

    /**
     * Creates new form requestDocument
     */
    public requestDocument() {
        initComponents();
        loadDocuments();
         setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        back_button1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        documentComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setText("Estimated Fee: ");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 310, 40));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REQUEST DOCUMENT");

        back_button1.setBackground(new java.awt.Color(255, 255, 255));
        back_button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        back_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_button1.setText("<");
        back_button1.setOpaque(true);
        back_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(back_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));

        name1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name1.setText("Document Type");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, 40));

        name2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name2.setText("Purpose");
        jPanel1.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 170, 40));

        documentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(documentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 180, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 260, 120));

        submit.setText("Submit Request");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void documentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentComboBoxActionPerformed

        DocumentItem selected =
            (DocumentItem) documentComboBox.getSelectedItem();

        if (selected != null) {
            name.setText("Estimated Fee: ₱" + selected.getFee());
        }
    }//GEN-LAST:event_documentComboBoxActionPerformed

    private void back_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button1MouseClicked
        this.dispose(); // Close current windo
      
    }//GEN-LAST:event_back_button1MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        DocumentItem selected =
            (DocumentItem) documentComboBox.getSelectedItem();

        if (selected == null) {
            JOptionPane.showMessageDialog(this,
                "Please select a document.",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        String purpose = jTextArea1.getText().trim();

        if (purpose.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Purpose cannot be empty.",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            connectDB db = new connectDB();
            Connection conn = db.getConnection();

            // 🔎 Get resident_id from users table
            String getResidentSql =
                "SELECT resident_id FROM users WHERE user_id = ?";
            PreparedStatement pst1 =
                conn.prepareStatement(getResidentSql);
            pst1.setInt(1,
                Config.User.getInstance().getUserId());

            ResultSet rs = pst1.executeQuery();

            Integer residentId = null;
            if (rs.next()) {
                residentId = (Integer) rs.getObject("resident_id");
            }

            rs.close();
            pst1.close();

            if (residentId == null) {
                JOptionPane.showMessageDialog(this,
                    "Resident profile not linked.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 📝 Insert request
            String insertSql =
                "INSERT INTO requests (resident_id, document_id, purpose) " +
                "VALUES (?, ?, ?)";

            PreparedStatement pst2 =
                conn.prepareStatement(insertSql);

            pst2.setInt(1, residentId);
            pst2.setInt(2, selected.getId());
            pst2.setString(3, purpose);

            pst2.executeUpdate();
            pst2.close();
            conn.close();

            JOptionPane.showMessageDialog(this,
                "Request submitted successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

            // Clear form
            documentComboBox.setSelectedIndex(-1);
            jTextArea1.setText("");
            name.setText("Estimated Fee:");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitActionPerformed
    private void loadDocuments() {

    try {
        connectDB db = new connectDB();
        Connection conn = db.getConnection();

       String sql = "SELECT document_id, document_name, fee FROM documents";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        documentComboBox.removeAllItems();

        documentComboBox.addItem(null); // Optional first blank

        while (rs.next()) {
            int id = rs.getInt("document_id");
            String name = rs.getString("document_name");
            double fee = rs.getDouble("fee");

            documentComboBox.addItem(new DocumentItem(id, name, fee));
        }

        rs.close();
        pst.close();
        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(requestDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(requestDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(requestDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(requestDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new requestDocument().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_button;
    private javax.swing.JLabel back_button1;
    private javax.swing.JComboBox<DocumentItem> documentComboBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
