/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residents;

import javax.swing.JOptionPane;


public class residentProfile extends javax.swing.JFrame {

    /**
     * Creates new form residentProfile
     */
    public residentProfile() {
        initComponents();
          setLocationRelativeTo(null);
           loadResidentProfile();
    }
    private void loadResidentProfile() {

        try {
            config.connectDB db = new config.connectDB();
            java.sql.Connection conn = db.getConnection();

            String sql =
                "SELECT r.* FROM residents r " +
                "JOIN users u ON r.resident_id = u.resident_id " +
                "WHERE u.user_id = ?";

            java.sql.PreparedStatement pst =
                conn.prepareStatement(sql);

            pst.setInt(1, Config.User.getInstance().getUserId());

            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                firstName.setText(rs.getString("first_name"));
                middleName.setText(rs.getString("middle_name"));
                lastName.setText(rs.getString("last_name"));
                birthdate.setText(rs.getString("birthdate"));
                contactNumber.setText(rs.getString("contact_number"));
                address.setText(rs.getString("address"));
                purok.setText(rs.getString("purok"));

                genderCombo.setSelectedItem(rs.getString("gender"));
                civilStatus.setSelectedItem(rs.getString("civil_status"));

                submit.setText("Update Profile"); // change button label
            }

            rs.close();
            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error loading profile: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        back_button1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        name9 = new javax.swing.JLabel();
        name10 = new javax.swing.JLabel();
        name11 = new javax.swing.JLabel();
        name12 = new javax.swing.JLabel();
        name13 = new javax.swing.JLabel();
        name14 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        middleName = new javax.swing.JTextField();
        birthdate = new javax.swing.JTextField();
        genderCombo = new javax.swing.JComboBox<>();
        firstName = new javax.swing.JTextField();
        contactNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        purok = new javax.swing.JTextField();
        civilStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Profile");

        back_button1.setBackground(new java.awt.Color(255, 255, 255));
        back_button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        back_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_button1.setText("<");
        back_button1.setOpaque(true);
        back_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(back_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        name1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name1.setText("Address Information");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 170, 40));

        submit.setText("Submit ");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 240, 40));

        name3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name3.setText("Purok:");
        jPanel1.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 70, 40));

        name4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name4.setText("Last Name:");
        jPanel1.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 40));

        name5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name5.setText("Middle Name:");
        jPanel1.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 40));

        name7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name7.setText("Gender");
        jPanel1.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 40));

        name8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name8.setText("Birthdate");
        jPanel1.add(name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 40));

        name9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name9.setText("Civil Status");
        jPanel1.add(name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 100, 40));

        name10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name10.setText("Personal Information");
        jPanel1.add(name10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, 40));

        name11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name11.setText("First Name: ");
        jPanel1.add(name11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 40));

        name12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name12.setText("Contact Information");
        jPanel1.add(name12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 170, 40));

        name13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name13.setText("Contact Number:");
        jPanel1.add(name13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 160, 40));

        name14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name14.setText("Address");
        jPanel1.add(name14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 60, 40));
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, 40));
        jPanel1.add(middleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 160, 40));
        jPanel1.add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 160, 40));

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboActionPerformed(evt);
            }
        });
        jPanel1.add(genderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 160, 40));
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 160, 40));
        jPanel1.add(contactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 160, 40));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 240, 120));

        purok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purokActionPerformed(evt);
            }
        });
        jPanel1.add(purok, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 160, 40));

        civilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Widowed", "Separated" }));
        civilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilStatusActionPerformed(evt);
            }
        });
        jPanel1.add(civilStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button1MouseClicked
        this.dispose(); 

    }//GEN-LAST:event_back_button1MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        String fName = firstName.getText().trim();
        String mName = middleName.getText().trim();
        String lName = lastName.getText().trim();
        String bdate = birthdate.getText().trim();
        String gender = genderCombo.getSelectedItem().toString();
       String civil = civilStatus.getSelectedItem().toString();
        String contact = contactNumber.getText().trim();
        String addr = address.getText().trim();
        String purokText = purok.getText().trim();

        StringBuilder errors = new StringBuilder();

        // ================= VALIDATION =================
        if (fName.isEmpty()) errors.append("First Name is required.\n");
        if (lName.isEmpty()) errors.append("Last Name is required.\n");
        if (bdate.isEmpty()) errors.append("Birthdate is required.\n");
        if (civil.isEmpty()) errors.append("Civil Status is required.\n");
        if (contact.isEmpty()) {
            errors.append("Contact number is required.\n");
        } else if (!contact.matches("\\d{11}")) {
            errors.append("Contact number must be 11 digits.\n");
        }
        if (addr.isEmpty()) errors.append("Address is required.\n");
        if (purokText.isEmpty()) errors.append("Purok is required.\n");

        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this,
                errors.toString(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

    try {
       config.connectDB db = new config.connectDB();
       java.sql.Connection conn = db.getConnection();
       conn.setAutoCommit(false);

       // 🔎 Check if this user already has a resident_id
       String checkSql = "SELECT resident_id FROM users WHERE user_id = ?";
       java.sql.PreparedStatement checkPst = conn.prepareStatement(checkSql);
       checkPst.setInt(1, Config.User.getInstance().getUserId());
       java.sql.ResultSet checkRs = checkPst.executeQuery();

       Integer existingResidentId = null;

       if (checkRs.next()) {
           existingResidentId = (Integer) checkRs.getObject("resident_id");
       }

       checkRs.close();
       checkPst.close();

       if (existingResidentId != null) {

           // ================= UPDATE EXISTING RESIDENT =================
           String updateSql =
               "UPDATE residents SET " +
               "first_name=?, middle_name=?, last_name=?, birthdate=?, " +
               "gender=?, civil_status=?, contact_number=?, address=?, purok=? " +
               "WHERE resident_id=?";

           java.sql.PreparedStatement updatePst =
               conn.prepareStatement(updateSql);

           updatePst.setString(1, fName);
           updatePst.setString(2, mName);
           updatePst.setString(3, lName);
           updatePst.setString(4, bdate);
           updatePst.setString(5, gender);
           updatePst.setString(6, civil);
           updatePst.setString(7, contact);
           updatePst.setString(8, addr);
           updatePst.setString(9, purokText);
           updatePst.setInt(10, existingResidentId);

           updatePst.executeUpdate();
           updatePst.close();

       } else {

           // ================= INSERT NEW RESIDENT =================
           String insertSql =
               "INSERT INTO residents " +
               "(first_name, middle_name, last_name, birthdate, gender, civil_status, contact_number, address, purok, status) " +
               "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

           java.sql.PreparedStatement insertPst =
               conn.prepareStatement(insertSql,
                   java.sql.Statement.RETURN_GENERATED_KEYS);

           insertPst.setString(1, fName);
           insertPst.setString(2, mName);
           insertPst.setString(3, lName);
           insertPst.setString(4, bdate);
           insertPst.setString(5, gender);
           insertPst.setString(6, civil);
           insertPst.setString(7, contact);
           insertPst.setString(8, addr);
           insertPst.setString(9, purokText);
           insertPst.setString(10, "Active");

           insertPst.executeUpdate();

           java.sql.ResultSet keys = insertPst.getGeneratedKeys();
           int newResidentId = 0;

           if (keys.next()) {
               newResidentId = keys.getInt(1);
           }

           keys.close();
           insertPst.close();

           // 🔗 Link to users table
           String linkSql =
               "UPDATE users SET resident_id=? WHERE user_id=?";

           java.sql.PreparedStatement linkPst =
               conn.prepareStatement(linkSql);

           linkPst.setInt(1, newResidentId);
           linkPst.setInt(2, Config.User.getInstance().getUserId());

           linkPst.executeUpdate();
           linkPst.close();
       }

       conn.commit();
       conn.setAutoCommit(true);
       conn.close();

       JOptionPane.showMessageDialog(this,
           "Profile saved successfully!",
           "Success",
           JOptionPane.INFORMATION_MESSAGE);

       new residentDashboard().setVisible(true);
       this.dispose();

   } catch (Exception e) {
       JOptionPane.showMessageDialog(this,
           "Error: " + e.getMessage(),
           "Database Error",
           JOptionPane.ERROR_MESSAGE);
   }
    }//GEN-LAST:event_submitActionPerformed

    private void genderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboActionPerformed

    private void purokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purokActionPerformed

    private void civilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civilStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(residentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(residentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(residentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(residentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new residentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JLabel back_button1;
    private javax.swing.JTextField birthdate;
    private javax.swing.JComboBox<String> civilStatus;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JTextField firstName;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField middleName;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name10;
    private javax.swing.JLabel name11;
    private javax.swing.JLabel name12;
    private javax.swing.JLabel name13;
    private javax.swing.JLabel name14;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    private javax.swing.JLabel name9;
    private javax.swing.JTextField purok;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
