/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authentication;

import Config.User;
import config.connectDB;
import admin.adminDashboard;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import residents.residentDashboard;
import utils.HashUtil;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    connectDB db = new connectDB();
    public login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        errorlabelUser = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        errorlabelPass = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        user = new javax.swing.JLabel();
        pwl1 = new javax.swing.JLabel();
        login_button = new javax.swing.JPanel();
        llogin = new javax.swing.JLabel();
        usl2 = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPanel.setBackground(new java.awt.Color(207, 75, 0));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, 0, 1070, 790));

        loginPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 600));

        login.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOG IN");
        loginPanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 180, 70));

        errorlabelUser.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        loginPanel.add(errorlabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 280, 20));

        username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        loginPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 300, 40));

        errorlabelPass.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        loginPanel.add(errorlabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 280, 20));

        password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        loginPanel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 300, 40));

        user.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        user.setText("Username");
        loginPanel.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 300, 20));

        pwl1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        pwl1.setText("Password");
        loginPanel.add(pwl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 300, 20));

        login_button.setBackground(new java.awt.Color(221, 186, 125));
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_buttonMouseClicked(evt);
            }
        });
        login_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        llogin.setBackground(new java.awt.Color(58, 53, 80));
        llogin.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        llogin.setForeground(new java.awt.Color(255, 255, 255));
        llogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llogin.setText("LOGIN");
        llogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lloginMouseClicked(evt);
            }
        });
        login_button.add(llogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 60, 40));

        loginPanel.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 300, 40));

        usl2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usl2.setText("Don't have an account?");
        loginPanel.add(usl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 140, 20));

        register.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        register.setForeground(new java.awt.Color(39, 76, 119));
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("REGISTER HERE");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        loginPanel.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 120, 20));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon gamay.png"))); // NOI18N
        loginPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 760, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost

    String userText = username.getText().trim();

        if (userText.isEmpty()) {
            errorlabelUser.setForeground(Color.RED);
            errorlabelUser.setText("Username is required");
        } else {
            errorlabelUser.setText("");
            errorlabelUser.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usernameFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost

        String pass = new String(password.getPassword()).trim();

        if (pass.isEmpty()) {
            errorlabelPass.setForeground(Color.RED);
            errorlabelPass.setText("Password is required");
        } else {
            errorlabelPass.setText("");
            errorlabelPass.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_passwordFocusLost

    private void lloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lloginMouseClicked
    login_buttonMouseClicked(evt);
    }//GEN-LAST:event_lloginMouseClicked

    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseClicked
   String user = username.getText().trim();
    String pass = new String(password.getPassword()).trim();

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please fill in both fields.",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    connectDB db = new connectDB();
    Connection con = db.getConnection();

    if (con == null) {
        JOptionPane.showMessageDialog(this,
                "Database connection failed.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "SELECT user_id, password, status, role FROM users WHERE username = ?";

    try {
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, user);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            String storedPassword = rs.getString("password");
            String status = rs.getString("status");
            String roleFromDB = rs.getString("role");
            int userId = rs.getInt("user_id");

            if (storedPassword.equals(HashUtil.hashPassword(pass))) {

                if ("Inactive".equalsIgnoreCase(status)) {
                    JOptionPane.showMessageDialog(this,
                            "Your account is inactive.",
                            "Login Error",
                            JOptionPane.ERROR_MESSAGE);
                } else {

                    // Save session
                    User.getInstance().setUser(userId, user, roleFromDB);

                    JOptionPane.showMessageDialog(this,
                            "Login successful!",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);

                    this.dispose();

                    // Redirect based on role
                    if (roleFromDB.equalsIgnoreCase("Resident")) {
                        new residents.residentDashboard().setVisible(true);
                    } else {
                        new admin.adminDashboard().setVisible(true);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this,
                        "Invalid username or password.",
                        "Login Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Invalid username or password.",
                    "Login Error",
                    JOptionPane.ERROR_MESSAGE);
        }

        rs.close();
        pst.close();
        con.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,
                "Database error: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_login_buttonMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
       new register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorlabelPass;
    private javax.swing.JLabel errorlabelUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel llogin;
    private javax.swing.JLabel login;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel login_button;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel pwl1;
    private javax.swing.JLabel register;
    private javax.swing.JLabel user;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usl2;
    // End of variables declaration//GEN-END:variables
}
