/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authentication;

import config.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import utils.HashUtil;


public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
  
    public register() {
        initComponents();
                setLocationRelativeTo(null);

    }
    
    private boolean isEmailTaken(String email) {
        connectDB db = new connectDB();
        Connection con = db.getConnection();  
        String sql = "SELECT 1 FROM users WHERE email = ?";

        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, email);
            ResultSet rs = pst.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    private boolean isUsernameTaken(String username) {
    connectDB db = new connectDB();
    Connection con = db.getConnection();
    String sql = "SELECT 1 FROM users WHERE username = ?";

    try (PreparedStatement pst = con.prepareStatement(sql)) {
        pst.setString(1, username);
        ResultSet rs = pst.executeQuery();
        return rs.next();
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return false;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerPanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        welcome2 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        middlename = new javax.swing.JTextField();
        welcome6 = new javax.swing.JLabel();
        welcome7 = new javax.swing.JLabel();
        welcome8 = new javax.swing.JLabel();
        welcome9 = new javax.swing.JLabel();
        welcome10 = new javax.swing.JLabel();
        welcome11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        welcome12 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        personal = new javax.swing.JLabel();
        welcome14 = new javax.swing.JLabel();
        welcome15 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        welcome16 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        regsiter_button = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        welcome4 = new javax.swing.JLabel();
        welcome5 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        welcome1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(207, 75, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcome2.setForeground(new java.awt.Color(255, 255, 255));
        welcome2.setText("Last Name");
        jPanel2.add(welcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 180, 30));

        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 200, 40));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 40));

        middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameActionPerformed(evt);
            }
        });
        jPanel2.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 200, 40));

        welcome6.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        welcome6.setForeground(new java.awt.Color(255, 255, 255));
        welcome6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome6.setText("REGISTER");
        jPanel2.add(welcome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 250, 60));

        welcome7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        welcome7.setForeground(new java.awt.Color(255, 255, 255));
        welcome7.setText("Contact Information");
        jPanel2.add(welcome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 180, 30));

        welcome8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcome8.setForeground(new java.awt.Color(255, 255, 255));
        welcome8.setText("First Name");
        jPanel2.add(welcome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 180, 30));

        welcome9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcome9.setForeground(new java.awt.Color(255, 255, 255));
        welcome9.setText("Middle Name");
        jPanel2.add(welcome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 180, 30));

        welcome10.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        welcome10.setForeground(new java.awt.Color(255, 255, 255));
        welcome10.setText("Log In Credentials");
        jPanel2.add(welcome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 180, 30));

        welcome11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcome11.setForeground(new java.awt.Color(255, 255, 255));
        welcome11.setText("Email");
        jPanel2.add(welcome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 180, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 200, 40));

        welcome12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcome12.setForeground(new java.awt.Color(255, 255, 255));
        welcome12.setText("Contact Number");
        jPanel2.add(welcome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 180, 30));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 200, 40));

        personal.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        personal.setForeground(new java.awt.Color(255, 255, 255));
        personal.setText("Personal Information");
        jPanel2.add(personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 180, 30));

        welcome14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcome14.setForeground(new java.awt.Color(255, 255, 255));
        welcome14.setText("Role");
        jPanel2.add(welcome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 180, 30));

        welcome15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcome15.setForeground(new java.awt.Color(255, 255, 255));
        welcome15.setText("Username");
        jPanel2.add(welcome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 180, 30));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 200, 40));

        welcome16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcome16.setForeground(new java.awt.Color(255, 255, 255));
        welcome16.setText("Password");
        jPanel2.add(welcome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 180, 30));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Resident", "Barangay Captain", "Secretary", "Treasurer", "Barangay Official" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        jPanel2.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 200, 40));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 200, 40));

        regsiter_button.setBackground(new java.awt.Color(221, 186, 125));
        regsiter_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regsiter_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regsiter_button.setText("REGISTER");
        regsiter_button.setOpaque(true);
        regsiter_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regsiter_buttonMouseClicked(evt);
            }
        });
        jPanel2.add(regsiter_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 160, 40));

        registerPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 630, 600));

        logo.setBackground(new java.awt.Color(204, 204, 204));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon mas gamay.png"))); // NOI18N
        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 186, 125)));
        registerPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, -60, 1140, 670));

        welcome.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("REQUEST SYSTEM");
        registerPanel.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 340, 50));

        welcome4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        welcome4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome4.setText("Welcome ");
        registerPanel.add(welcome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, 60));

        welcome5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        welcome5.setForeground(new java.awt.Color(102, 102, 102));
        welcome5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome5.setText("Serving Documents, Serving the Community!");
        registerPanel.add(welcome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 340, 410, 40));

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOG IN ");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 186, 125), 2));
        login.setOpaque(true);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        registerPanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 160, 40));

        welcome1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome1.setText("BARANGAY DOCUMENT");
        registerPanel.add(welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 380, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void middlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void regsiter_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regsiter_buttonMouseClicked

    connectDB db = new connectDB();

    String firstNameText = firstname.getText().trim();
    String middleNameText = middlename.getText().trim();
    String lastNameText = lastname.getText().trim();
    String contactNumberText = contact.getText().trim();
    String usernameText = username.getText().trim();
    String emailText = email.getText().trim();
    String selectedRole = role.getSelectedItem().toString().trim();
    String passwordText = new String(password.getPassword());

    StringBuilder errorMessage = new StringBuilder();


        // First Name
        if (firstNameText.isEmpty()) {
            errorMessage.append("First Name cannot be empty.\n");
        }

        // Last Name
        if (lastNameText.isEmpty()) {
            errorMessage.append("Last Name cannot be empty.\n");
        }

        // Role
        if (role.getSelectedIndex() == 0) {
            errorMessage.append("Please select a role.\n");
        }

        // Contact Number
        if (contactNumberText.isEmpty()) {
            errorMessage.append("Contact number cannot be empty.\n");
        } else if (!contactNumberText.matches("\\d{11}")) {
            errorMessage.append("Contact number must be exactly 11 digits.\n");
        }

        // Email
        if (emailText.isEmpty()) {
            errorMessage.append("Email cannot be empty.\n");
        } else if (!emailText.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            errorMessage.append("Invalid email format.\n");
        } else if (isEmailTaken(emailText)) {
            errorMessage.append("Email already exists.\n");
        }

        // Username
        if (usernameText.isEmpty()) {
            errorMessage.append("Username cannot be empty.\n");
        } else if (isUsernameTaken(usernameText)) {
            errorMessage.append("Username already exists.\n");
        }

        // Password
        if (passwordText.isEmpty()) {
            errorMessage.append("Password cannot be empty.\n");
        } else if (passwordText.length() < 6) {
            errorMessage.append("Password must be at least 6 characters.\n");
        }

        // Final Validation Check
        if (errorMessage.length() > 0) {
            JOptionPane.showMessageDialog(this,
                    errorMessage.toString(),
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
          Connection conn = db.getConnection();

          String hashedPassword = HashUtil.hashPassword(passwordText);

          String userSql = "INSERT INTO users (first_name, middle_name, last_name, contact_number, role, email, username, password, status, resident_id) "
                  + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

          PreparedStatement pst = conn.prepareStatement(userSql);

          pst.setString(1, firstNameText);
          pst.setString(2, middleNameText);
          pst.setString(3, lastNameText);
          pst.setString(4, contactNumberText);
          pst.setString(5, selectedRole);
          pst.setString(6, emailText);
          pst.setString(7, usernameText);
          pst.setString(8, hashedPassword);

          // Optional logic:
          // Auto-activate residents, require approval for officials
          if (selectedRole.equalsIgnoreCase("Resident")) {
              pst.setString(9, "Active");
          } else {
              pst.setString(9, "Inactive");
          }

          pst.setNull(10, java.sql.Types.INTEGER); // resident_id = NULL

          pst.executeUpdate();
          pst.close();

          JOptionPane.showMessageDialog(this,
                  "Registration successful!",
                  "Success",
                  JOptionPane.INFORMATION_MESSAGE);

          new login().setVisible(true);
          this.dispose();

      } catch (SQLException ex) {
          JOptionPane.showMessageDialog(this,
                  "Error: " + ex.getMessage(),
                  "Database Error",
                  JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_regsiter_buttonMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
           new login().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel login;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField middlename;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel personal;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel regsiter_button;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JTextField username;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcome1;
    private javax.swing.JLabel welcome10;
    private javax.swing.JLabel welcome11;
    private javax.swing.JLabel welcome12;
    private javax.swing.JLabel welcome14;
    private javax.swing.JLabel welcome15;
    private javax.swing.JLabel welcome16;
    private javax.swing.JLabel welcome2;
    private javax.swing.JLabel welcome4;
    private javax.swing.JLabel welcome5;
    private javax.swing.JLabel welcome6;
    private javax.swing.JLabel welcome7;
    private javax.swing.JLabel welcome8;
    private javax.swing.JLabel welcome9;
    // End of variables declaration//GEN-END:variables
}
