/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import config.connectDB;

public class addResident extends javax.swing.JFrame {

    /**
     * Creates new form addResident
     */
    public addResident() {
        initComponents();
        setLocationRelativeTo(null);
        status.setText("Active");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        welcome4 = new javax.swing.JLabel();
        lastname2 = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        middlename = new javax.swing.JTextField();
        welcome6 = new javax.swing.JLabel();
        welcome7 = new javax.swing.JLabel();
        welcome8 = new javax.swing.JLabel();
        welcome9 = new javax.swing.JLabel();
        welcome11 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        welcome12 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        personal = new javax.swing.JLabel();
        welcome14 = new javax.swing.JLabel();
        welcome15 = new javax.swing.JLabel();
        welcome16 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        back_button = new javax.swing.JLabel();
        addResident = new javax.swing.JLabel();
        civilStatus = new javax.swing.JComboBox<>();
        purok = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        welcome17 = new javax.swing.JLabel();
        welcome5 = new javax.swing.JLabel();
        birthdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 102, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome4.setText("Birthdate");
        jPanel6.add(welcome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 180, 30));

        lastname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastname2ActionPerformed(evt);
            }
        });
        jPanel6.add(lastname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 40));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel6.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 40));

        middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameActionPerformed(evt);
            }
        });
        jPanel6.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 40));

        welcome6.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        welcome6.setForeground(new java.awt.Color(255, 255, 255));
        welcome6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome6.setText("Add Resident");
        jPanel6.add(welcome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 250, 60));

        welcome7.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        welcome7.setForeground(new java.awt.Color(255, 255, 255));
        welcome7.setText("Contact Information");
        jPanel6.add(welcome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 240, 30));

        welcome8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome8.setText("First Name");
        jPanel6.add(welcome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));

        welcome9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome9.setText("Middle Name");
        jPanel6.add(welcome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 30));

        welcome11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome11.setText("Status");
        jPanel6.add(welcome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 180, 30));

        status.setEditable(false);
        status.setEnabled(false);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel6.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 200, 40));

        welcome12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome12.setText("Contact Number");
        jPanel6.add(welcome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 180, 30));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel6.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 200, 40));

        personal.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        personal.setForeground(new java.awt.Color(255, 255, 255));
        personal.setText("Personal Information");
        jPanel6.add(personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 30));

        welcome14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome14.setText("Gender");
        jPanel6.add(welcome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 180, 30));

        welcome15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome15.setText("Civil Status");
        jPanel6.add(welcome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 180, 30));

        welcome16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome16.setText("Purok");
        jPanel6.add(welcome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 180, 30));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel6.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, 40));

        back_button.setBackground(new java.awt.Color(255, 255, 255));
        back_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        back_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_button.setText("<");
        back_button.setOpaque(true);
        back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_buttonMouseClicked(evt);
            }
        });
        jPanel6.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 50, 30));

        addResident.setBackground(new java.awt.Color(255, 255, 255));
        addResident.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addResident.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addResident.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-register-20.png"))); // NOI18N
        addResident.setOpaque(true);
        addResident.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addResidentMouseClicked(evt);
            }
        });
        jPanel6.add(addResident, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 50, 30));

        civilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Widowed", " " }));
        civilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilStatusActionPerformed(evt);
            }
        });
        jPanel6.add(civilStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, 40));

        purok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purokActionPerformed(evt);
            }
        });
        jPanel6.add(purok, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 200, 40));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel6.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 200, 40));

        welcome17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome17.setText("Address");
        jPanel6.add(welcome17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 180, 30));

        welcome5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome5.setText("Last Name");
        jPanel6.add(welcome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 180, 30));

        birthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateActionPerformed(evt);
            }
        });
        jPanel6.add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 200, 40));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastname2ActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void middlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
       residentsManage rm = new residentsManage();
        rm.setVisible(true);
        rm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_back_buttonMouseClicked
    public void clearFields(){

        firstname.setText("");
        middlename.setText("");
        lastname2.setText("");
        birthdate.setText("");
        contact.setText("");
        address.setText("");
        purok.setText("");

        gender.setSelectedIndex(0);
        civilStatus.setSelectedIndex(0);

    }
    private void addResidentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addResidentMouseClicked

        if(firstname.getText().isEmpty() || lastname2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"First name and Last name are required.");
            return;
        }
        if(birthdate.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Birthdate is required.");
            return;
        }
        if(contact.getText().length() < 11){
            JOptionPane.showMessageDialog(null,"Invalid contact number.");
            return;
        }
        try {

            String sql = "INSERT INTO residents "
                    + "(first_name, middle_name, last_name, birthdate, gender, civil_status, contact_number, address, purok, status) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            config.connectDB db = new config.connectDB();
            java.sql.Connection conn = db.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, firstname.getText());
            pst.setString(2, middlename.getText());
            pst.setString(3, lastname2.getText());
            pst.setString(4, birthdate.getText());
            pst.setString(5, gender.getSelectedItem().toString());
            pst.setString(6, civilStatus.getSelectedItem().toString());
            pst.setString(7, contact.getText());
            pst.setString(8, address.getText());
            pst.setString(9, purok.getText());
            pst.setString(10, status.getText());

           pst.executeUpdate();
            pst.close();
            conn.close();
            JOptionPane.showMessageDialog(null,"Resident added successfully!");

            clearFields();
            new residentsManage().setVisible(true);
            this.dispose();
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_addResidentMouseClicked

    private void civilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civilStatusActionPerformed

    private void purokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purokActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void birthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addResident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addResident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addResident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addResident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addResident().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addResident;
    private javax.swing.JTextField address;
    private javax.swing.JLabel back_button;
    private javax.swing.JTextField birthdate;
    private javax.swing.JComboBox<String> civilStatus;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lastname2;
    private javax.swing.JTextField middlename;
    private javax.swing.JLabel personal;
    private javax.swing.JTextField purok;
    private javax.swing.JTextField status;
    private javax.swing.JLabel welcome11;
    private javax.swing.JLabel welcome12;
    private javax.swing.JLabel welcome14;
    private javax.swing.JLabel welcome15;
    private javax.swing.JLabel welcome16;
    private javax.swing.JLabel welcome17;
    private javax.swing.JLabel welcome4;
    private javax.swing.JLabel welcome5;
    private javax.swing.JLabel welcome6;
    private javax.swing.JLabel welcome7;
    private javax.swing.JLabel welcome8;
    private javax.swing.JLabel welcome9;
    // End of variables declaration//GEN-END:variables
}
