/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Color;
import javax.swing.JOptionPane;
import Config.User;

public class adminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public adminDashboard() {
    initComponents();
     setLocationRelativeTo(null);
        if (User.getInstance().getUserId() == 0) {
            JOptionPane.showMessageDialog(this, "Please login first.");
            new authentication.login().setVisible(true);
            this.dispose();
            return;
        }

        name.setText(User.getInstance().getUsername());
        brgyRoleInternal1.setText(User.getInstance().getRole());
        brgyrole.setText(User.getInstance().getRole());
    }
    
    
        Color hoverColor = new Color (255,0,51);
        Color navColor = new Color (255,102,51);
        
        private void openFrame(javax.swing.JFrame frame) {
                this.dispose();        // close current window
                frame.setVisible(true); // open new window
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        welcome4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dashPanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        residentsPanel = new javax.swing.JPanel();
        residents = new javax.swing.JLabel();
        requestPanel = new javax.swing.JPanel();
        request = new javax.swing.JLabel();
        issuancePanel = new javax.swing.JPanel();
        issuance = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        users1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        brgyrole = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        brgyRoleInternal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        welcome4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome4.setText("B D R S");
        jPanel4.add(welcome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ChatGPT Image Feb 19, 2026, 10_44_19 PM (1).png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        dashPanel.setBackground(new java.awt.Color(255, 102, 51));
        dashPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashPanelMouseExited(evt);
            }
        });
        dashPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashPanel.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(dashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, -1));

        profilePanel.setBackground(new java.awt.Color(255, 102, 51));
        profilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilePanelMouseExited(evt);
            }
        });
        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profilePanel.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(profilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, -1));

        residentsPanel.setBackground(new java.awt.Color(255, 102, 51));
        residentsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                residentsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                residentsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                residentsPanelMouseExited(evt);
            }
        });
        residentsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        residents.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        residents.setForeground(new java.awt.Color(255, 255, 255));
        residents.setText("Manage Residents");
        residentsPanel.add(residents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 40));

        jPanel2.add(residentsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 170, -1));

        requestPanel.setBackground(new java.awt.Color(255, 102, 51));
        requestPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                requestPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                requestPanelMouseExited(evt);
            }
        });
        requestPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        request.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        request.setForeground(new java.awt.Color(255, 255, 255));
        request.setText("Request");
        requestPanel.add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(requestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 170, -1));

        issuancePanel.setBackground(new java.awt.Color(255, 102, 51));
        issuancePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuancePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issuancePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issuancePanelMouseExited(evt);
            }
        });
        issuancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issuance.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        issuance.setForeground(new java.awt.Color(255, 255, 255));
        issuance.setText("Documents");
        issuancePanel.add(issuance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(issuancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 170, -1));

        logoutPanel.setBackground(new java.awt.Color(153, 51, 0));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelMouseExited(evt);
            }
        });
        logoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LOG OUT");
        logoutPanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 40));

        jPanel2.add(logoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 140, -1));

        userPanel.setBackground(new java.awt.Color(255, 102, 51));
        userPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userPanelMouseExited(evt);
            }
        });
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        users1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        users1.setForeground(new java.awt.Color(255, 255, 255));
        users1.setText("Manage Users");
        users1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                users1MouseClicked(evt);
            }
        });
        userPanel.add(users1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 610));

        jPanel5.setBackground(new java.awt.Color(255, 102, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brgyrole.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        brgyrole.setForeground(new java.awt.Color(255, 255, 255));
        brgyrole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        brgyrole.setText("Dashboard");
        jPanel5.add(brgyrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 50));

        title.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Dashboard");
        jPanel5.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 730, 50));

        name.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("NAME");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 380, 70));

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOME BACK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 380, 70));

        brgyRoleInternal1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        brgyRoleInternal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brgyRoleInternal1.setText("ROLE");
        jPanel1.add(brgyRoleInternal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 380, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashPanelMouseClicked

    private void dashPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPanelMouseEntered
        dashPanel.setBackground(hoverColor);
    }//GEN-LAST:event_dashPanelMouseEntered

    private void dashPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPanelMouseExited
        dashPanel.setBackground(navColor);
    }//GEN-LAST:event_dashPanelMouseExited

    private void profilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseClicked
    }//GEN-LAST:event_profilePanelMouseClicked

    private void profilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseEntered
        profilePanel.setBackground(hoverColor);
    }//GEN-LAST:event_profilePanelMouseEntered

    private void profilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseExited
        profilePanel.setBackground(navColor);
    }//GEN-LAST:event_profilePanelMouseExited

    private void residentsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residentsPanelMouseClicked
        this.dispose(); // close current window

        new residentsManage().setVisible(true);
    }//GEN-LAST:event_residentsPanelMouseClicked

    private void residentsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residentsPanelMouseEntered
        residentsPanel.setBackground(hoverColor);
    }//GEN-LAST:event_residentsPanelMouseEntered

    private void residentsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residentsPanelMouseExited
        residentsPanel.setBackground(navColor);
    }//GEN-LAST:event_residentsPanelMouseExited

    private void requestPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestPanelMouseClicked
        this.dispose(); // close current window
        new requestManage().setVisible(true);
    }//GEN-LAST:event_requestPanelMouseClicked

    private void requestPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestPanelMouseEntered
        requestPanel.setBackground(hoverColor);
    }//GEN-LAST:event_requestPanelMouseEntered

    private void requestPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestPanelMouseExited
        requestPanel.setBackground(navColor);
    }//GEN-LAST:event_requestPanelMouseExited

    private void issuancePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuancePanelMouseClicked
           openFrame(new documentsManage());
    }//GEN-LAST:event_issuancePanelMouseClicked

    private void issuancePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuancePanelMouseEntered
        issuancePanel.setBackground(hoverColor);
    }//GEN-LAST:event_issuancePanelMouseEntered

    private void issuancePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuancePanelMouseExited
        issuancePanel.setBackground(navColor);
    }//GEN-LAST:event_issuancePanelMouseExited

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked

        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {
            User.getInstance().clearSession();
            new authentication.login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void logoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseEntered

    }//GEN-LAST:event_logoutPanelMouseEntered

    private void logoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseExited

    }//GEN-LAST:event_logoutPanelMouseExited

    private void userPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseClicked
    }//GEN-LAST:event_userPanelMouseClicked

    private void userPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userPanelMouseEntered

    private void userPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_userPanelMouseExited

    private void users1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users1MouseClicked
        // TODO add your handling code here:
        new userManage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_users1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brgyRoleInternal1;
    private javax.swing.JLabel brgyrole;
    private javax.swing.JPanel dashPanel;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel issuance;
    private javax.swing.JPanel issuancePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel request;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JLabel residents;
    private javax.swing.JPanel residentsPanel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel users1;
    private javax.swing.JLabel welcome4;
    // End of variables declaration//GEN-END:variables
}
