/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.print.PrinterJob;

/**
 *
 * @author Administrator
 */
public class BarangayClearance extends javax.swing.JFrame {

    /**
     * Creates new form BarangayClearance
     */
    public BarangayClearance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 1200));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barangay_clearance_resized.png"))); // NOI18N
        jScrollPane1.setViewportView(jLabel1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 720, 530));

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         btnPrintActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangayClearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangayClearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangayClearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangayClearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangayClearance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {
        // Ask user where to save
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Save Barangay Clearance as PDF");
    fileChooser.setSelectedFile(new java.io.File("BarangayClearance.pdf"));

    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection != javax.swing.JFileChooser.APPROVE_OPTION) return;

    String filePath = fileChooser.getSelectedFile().getAbsolutePath();
    if (!filePath.endsWith(".pdf")) filePath += ".pdf";

    // Get image from jLabel1
    java.awt.Image img = ((javax.swing.ImageIcon) jLabel1.getIcon()).getImage();
    int imgWidth = img.getWidth(null);
    int imgHeight = img.getHeight(null);

    // Convert to BufferedImage
    java.awt.image.BufferedImage buffered = new java.awt.image.BufferedImage(
        imgWidth, imgHeight, java.awt.image.BufferedImage.TYPE_INT_RGB
    );
    java.awt.Graphics2D g2d = buffered.createGraphics();
    g2d.setColor(java.awt.Color.WHITE);
    g2d.fillRect(0, 0, imgWidth, imgHeight);
    g2d.drawImage(img, 0, 0, null);
    g2d.dispose();

    try {
        // Convert BufferedImage to byte array
        java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
        javax.imageio.ImageIO.write(buffered, "png", baos);
        byte[] imageBytes = baos.toByteArray();

        // Create PDF using iText
        com.itextpdf.text.Document document = new com.itextpdf.text.Document(
            new com.itextpdf.text.Rectangle(imgWidth, imgHeight), 0, 0, 0, 0
        );

        com.itextpdf.text.pdf.PdfWriter.getInstance(
            document,
            new java.io.FileOutputStream(filePath)
        );

        document.open();

        // Add image to PDF
        com.itextpdf.text.Image pdfImg = com.itextpdf.text.Image.getInstance(imageBytes);
        pdfImg.setAbsolutePosition(0, 0);
        pdfImg.scaleToFit(imgWidth, imgHeight);
        document.add(pdfImg);

        document.close();

        // Open file explorer to show saved PDF
        java.awt.Desktop.getDesktop().open(
            new java.io.File(filePath).getParentFile()
        );

        javax.swing.JOptionPane.showMessageDialog(this,
            "PDF saved successfully!\nLocation: " + filePath);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error saving PDF: " + e.getMessage());
    }
    }

}  // ← this is your existing closing 

