/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import javax.swing.JOptionPane;


public class createUser extends javax.swing.JFrame {

    /**
     * Creates new form createUser
     */
    public createUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        welcome4 = new javax.swing.JLabel();
        lastname2 = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        middlename = new javax.swing.JTextField();
        welcome6 = new javax.swing.JLabel();
        welcome7 = new javax.swing.JLabel();
        welcome8 = new javax.swing.JLabel();
        welcome9 = new javax.swing.JLabel();
        welcome10 = new javax.swing.JLabel();
        welcome11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        welcome12 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        personal = new javax.swing.JLabel();
        welcome14 = new javax.swing.JLabel();
        welcome15 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        welcome16 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        back_button = new javax.swing.JLabel();
        register_button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 102, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome4.setText("Last Name");
        jPanel6.add(welcome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 180, 30));

        lastname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastname2ActionPerformed(evt);
            }
        });
        jPanel6.add(lastname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 40));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel6.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 40));

        middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameActionPerformed(evt);
            }
        });
        jPanel6.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 40));

        welcome6.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        welcome6.setForeground(new java.awt.Color(255, 255, 255));
        welcome6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome6.setText("REGISTER");
        jPanel6.add(welcome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 250, 60));

        welcome7.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        welcome7.setForeground(new java.awt.Color(255, 255, 255));
        welcome7.setText("Contact Information");
        jPanel6.add(welcome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 180, 30));

        welcome8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome8.setText("First Name");
        jPanel6.add(welcome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));

        welcome9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome9.setText("Middle Name");
        jPanel6.add(welcome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 30));

        welcome10.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        welcome10.setForeground(new java.awt.Color(255, 255, 255));
        welcome10.setText("Log In Credentials");
        jPanel6.add(welcome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 30));

        welcome11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome11.setText("Email");
        jPanel6.add(welcome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 180, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel6.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 200, 40));

        welcome12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome12.setText("Contact Number");
        jPanel6.add(welcome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 180, 30));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel6.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 200, 40));

        personal.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        personal.setForeground(new java.awt.Color(255, 255, 255));
        personal.setText("Personal Information");
        jPanel6.add(personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 30));

        welcome14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome14.setText("Role");
        jPanel6.add(welcome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 180, 30));

        welcome15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome15.setText("Username");
        jPanel6.add(welcome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 180, 30));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel6.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, 40));

        welcome16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        welcome16.setText("Password");
        jPanel6.add(welcome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 180, 30));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Resident", "Barangay Captain", "Secretary", "Treasurer", "Barangay Official" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        jPanel6.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, 40));
        jPanel6.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 200, 40));

        back_button.setBackground(new java.awt.Color(255, 255, 255));
        back_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        back_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_button.setText("<");
        back_button.setOpaque(true);
        back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_buttonMouseClicked(evt);
            }
        });
        jPanel6.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 50, 30));

        register_button.setBackground(new java.awt.Color(255, 255, 255));
        register_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        register_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-register-20.png"))); // NOI18N
        register_button.setOpaque(true);
        register_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_buttonMouseClicked(evt);
            }
        });
        jPanel6.add(register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 50, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastname2ActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void middlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
        this.dispose(); // Close current window

        userManage manage = new userManage();
        manage.setLocationRelativeTo(null); // center
        manage.setVisible(true);
    }//GEN-LAST:event_back_buttonMouseClicked

    private void register_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseClicked

        String firstNameText = firstname.getText().trim();
        String middleNameText = middlename.getText().trim();
        String lastNameText = lastname2.getText().trim();
        String contactNumberText = contact.getText().trim();
        String usernameText = username.getText().trim();
        String emailText = email.getText().trim();
        String selectedRole = role.getSelectedItem().toString();
        String passwordText = new String(password.getPassword()).trim();

        StringBuilder errors = new StringBuilder();

        // ===== REQUIRED FIELDS =====
        if (firstNameText.isEmpty())
            errors.append("• First name is required.\n");

        if (lastNameText.isEmpty())
            errors.append("• Last name is required.\n");

        if (role.getSelectedIndex() == 0)
            errors.append("• Please select a role.\n");

        if (emailText.isEmpty())
            errors.append("• Email is required.\n");

        if (usernameText.isEmpty())
            errors.append("• Username is required.\n");

        if (passwordText.isEmpty())
            errors.append("• Password is required.\n");

        // ===== FORMAT VALIDATION =====
        if (!emailText.isEmpty() &&
                !emailText.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"))
            errors.append("• Invalid email format.\n");

        if (!contactNumberText.isEmpty() &&
                !contactNumberText.matches("\\d{11}"))
            errors.append("• Contact number must be 11 digits.\n");

        if (!passwordText.isEmpty()) {

            if (passwordText.length() < 8)
                errors.append("• Password must be at least 6 characters.\n");

           
        }

        // ===== STOP IF ERRORS =====
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this,
                    errors.toString(),
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ===== CHECK DUPLICATES =====
        if (isEmailTaken(emailText)) {
            JOptionPane.showMessageDialog(this,
                    "Email already exists.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (isUsernameTaken(usernameText)) {
            JOptionPane.showMessageDialog(this,
                    "Username already exists.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ===== HASH PASSWORD =====
        String hashedPassword = utils.HashUtil.hashPassword(passwordText);

        String sql = "INSERT INTO users (first_name, middle_name, last_name, contact_number, role, email, username, password, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try {
            config.connectDB db = new config.connectDB();
            java.sql.Connection conn = db.getConnection();

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, firstNameText);
            pst.setString(2, middleNameText);
            pst.setString(3, lastNameText);
            pst.setString(4, contactNumberText);
            pst.setString(5, selectedRole);
            pst.setString(6, emailText);
            pst.setString(7, usernameText);
            pst.setString(8, hashedPassword);
            pst.setString(9, "Inactive");

            pst.executeUpdate();

            pst.close();
            conn.close();

            JOptionPane.showMessageDialog(this,
                    "User registered successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Database error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_register_buttonMouseClicked

    private void clearFields() {
    firstname.setText("");
    middlename.setText("");
    lastname2.setText("");
    contact.setText("");
    username.setText("");
    email.setText("");
    password.setText("");
    role.setSelectedIndex(0);
}
    private boolean isEmailTaken(String email) {
    try {
        config.connectDB db = new config.connectDB();
        java.sql.Connection conn = db.getConnection();

        String sql = "SELECT user_id FROM users WHERE email = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, email);

        java.sql.ResultSet rs = pst.executeQuery();

        boolean exists = rs.next();

        rs.close();
        pst.close();
        conn.close();

        return exists;

    } catch (Exception e) {
        return false;
    }
}
    private boolean isUsernameTaken(String username) {
    try {
        config.connectDB db = new config.connectDB();
        java.sql.Connection conn = db.getConnection();

        String sql = "SELECT user_id FROM users WHERE username = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);

        java.sql.ResultSet rs = pst.executeQuery();

        boolean exists = rs.next();

        rs.close();
        pst.close();
        conn.close();

        return exists;

    } catch (Exception e) {
        return false;
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_button;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lastname2;
    private javax.swing.JTextField middlename;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel personal;
    private javax.swing.JLabel register_button;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JTextField username;
    private javax.swing.JLabel welcome10;
    private javax.swing.JLabel welcome11;
    private javax.swing.JLabel welcome12;
    private javax.swing.JLabel welcome14;
    private javax.swing.JLabel welcome15;
    private javax.swing.JLabel welcome16;
    private javax.swing.JLabel welcome4;
    private javax.swing.JLabel welcome6;
    private javax.swing.JLabel welcome7;
    private javax.swing.JLabel welcome8;
    private javax.swing.JLabel welcome9;
    // End of variables declaration//GEN-END:variables
}
