/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import javax.swing.JOptionPane;


public class editUser extends javax.swing.JFrame {

    /**
     * Creates new form editUser
     */
    private int userId; // store the ID of the user being edited
    public editUser() {

    initComponents();
    setLocationRelativeTo(null);

    }

    public void setUserData(int userId,
                        String firstName,
                        String middleName,
                        String lastName,
                        String email,
                        String contactNumber,
                        String roleValue,
                        String usernameValue) {

            this.userId = userId;

            firstname.setText(firstName);
            middlename.setText(middleName);
            lastname.setText(lastName);
            em.setText(email);
            contact.setText(contactNumber);
            user.setText(usernameValue);
            role.setSelectedItem(roleValue);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        welcome2 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        middlename = new javax.swing.JTextField();
        welcome6 = new javax.swing.JLabel();
        welcome7 = new javax.swing.JLabel();
        welcome8 = new javax.swing.JLabel();
        welcome9 = new javax.swing.JLabel();
        welcome10 = new javax.swing.JLabel();
        welcome11 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        welcome12 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        personal = new javax.swing.JLabel();
        welcome14 = new javax.swing.JLabel();
        welcome15 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        welcome16 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        pass = new javax.swing.JPasswordField();
        back_button = new javax.swing.JLabel();
        save_button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        welcome2.setForeground(new java.awt.Color(255, 255, 255));
        welcome2.setText("Last Name");
        jPanel2.add(welcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 30));

        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, 40));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 40));

        middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameActionPerformed(evt);
            }
        });
        jPanel2.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 40));

        welcome6.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        welcome6.setForeground(new java.awt.Color(255, 255, 255));
        welcome6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome6.setText("UPDATE ");
        jPanel2.add(welcome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 250, 60));

        welcome7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        welcome7.setForeground(new java.awt.Color(255, 255, 255));
        welcome7.setText("Contact Details");
        jPanel2.add(welcome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 180, 30));

        welcome8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        welcome8.setForeground(new java.awt.Color(255, 255, 255));
        welcome8.setText("First Name");
        jPanel2.add(welcome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 30));

        welcome9.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        welcome9.setForeground(new java.awt.Color(255, 255, 255));
        welcome9.setText("Middle Name");
        jPanel2.add(welcome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 30));

        welcome10.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        welcome10.setForeground(new java.awt.Color(255, 255, 255));
        welcome10.setText("Log In Credentials");
        jPanel2.add(welcome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 180, 30));

        welcome11.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        welcome11.setForeground(new java.awt.Color(255, 255, 255));
        welcome11.setText("Email");
        jPanel2.add(welcome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 180, 30));

        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        jPanel2.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 200, 40));

        welcome12.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        welcome12.setForeground(new java.awt.Color(255, 255, 255));
        welcome12.setText("Contact Number");
        jPanel2.add(welcome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 180, 30));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 200, 40));

        personal.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        personal.setForeground(new java.awt.Color(255, 255, 255));
        personal.setText("Personal Information");
        jPanel2.add(personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        welcome14.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        welcome14.setForeground(new java.awt.Color(255, 255, 255));
        welcome14.setText("Role");
        jPanel2.add(welcome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 180, 30));

        welcome15.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        welcome15.setForeground(new java.awt.Color(255, 255, 255));
        welcome15.setText("Username");
        jPanel2.add(welcome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 180, 30));

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 200, 40));

        welcome16.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        welcome16.setForeground(new java.awt.Color(255, 255, 255));
        welcome16.setText("Password");
        jPanel2.add(welcome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 180, 30));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Resident", "Barangay Captain", "Secretary", "Treasurer", "Barangay Official" }));
        jPanel2.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 200, 40));
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 200, 40));

        back_button.setBackground(new java.awt.Color(255, 255, 255));
        back_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 102, 51));
        back_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_button.setText("BACK");
        back_button.setOpaque(true);
        back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_buttonMouseClicked(evt);
            }
        });
        jPanel2.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 160, 40));

        save_button.setBackground(new java.awt.Color(255, 255, 255));
        save_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 102, 51));
        save_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_button.setText("SAVE");
        save_button.setOpaque(true);
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_buttonMouseClicked(evt);
            }
        });
        jPanel2.add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 160, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void middlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
        this.dispose();

        
    }//GEN-LAST:event_back_buttonMouseClicked

    private void save_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseClicked

        String firstNameText = firstname.getText().trim();
        String middleNameText = middlename.getText().trim();
        String lastNameText = lastname.getText().trim();
        String emailText = em.getText().trim();
        String contactText = contact.getText().trim();
        String roleText = role.getSelectedItem().toString();
        String usernameText = user.getText().trim();
        String passwordText = new String(pass.getPassword()).trim();

       StringBuilder errors = new StringBuilder();

        // ===== REQUIRED FIELDS =====
        if (firstNameText.isEmpty())
            errors.append("• First name is required.\n");

        if (lastNameText.isEmpty())
            errors.append("• Last name is required.\n");

        if (emailText.isEmpty())
            errors.append("• Email is required.\n");

        if (usernameText.isEmpty())
            errors.append("• Username is required.\n");

        // ===== ROLE VALIDATION =====
        if (role.getSelectedIndex() == 0)
            errors.append("• Please select a valid role.\n");

        // ===== EMAIL FORMAT =====
        if (!emailText.isEmpty() &&
                !emailText.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            errors.append("• Invalid email format.\n");
        }

        // ===== CONTACT NUMBER =====
        if (!contactText.isEmpty() &&
                !contactText.matches("\\d{11}")) {
            errors.append("• Contact number must be exactly 11 digits.\n");
        }

        // ===== USERNAME RULE =====
        if (!usernameText.isEmpty() &&
                usernameText.length() < 4) {
            errors.append("• Username must be at least 4 characters.\n");
        }

        // ===== PASSWORD RULE (only if user entered one) =====
        if (!passwordText.isEmpty()) {

            if (passwordText.length() < 8)
                errors.append("• Password must be at least 6 characters.\n");

           
        }

        // ===== SHOW ERRORS IF ANY =====
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this,
                    errors.toString(),
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            config.connectDB db = new config.connectDB();
            java.sql.Connection conn = db.getConnection();

            String sql;

            // If password field is empty → don't update password
            if (passwordText.isEmpty()) {

                sql = "UPDATE users SET first_name=?, middle_name=?, last_name=?, email=?, contact_number=?, role=?, username=? WHERE user_id=?";

                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, firstNameText);
                pst.setString(2, middleNameText);
                pst.setString(3, lastNameText);
                pst.setString(4, emailText);
                pst.setString(5, contactText);
                pst.setString(6, roleText);
                pst.setString(7, usernameText);
                pst.setInt(8, userId);

                pst.executeUpdate();
                pst.close();

            } else {

                // Hash new password
                String hashedPassword = utils.HashUtil.hashPassword(passwordText);

                sql = "UPDATE users SET first_name=?, middle_name=?, last_name=?, email=?, contact_number=?, role=?, username=?, password=? WHERE user_id=?";

                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, firstNameText);
                pst.setString(2, middleNameText);
                pst.setString(3, lastNameText);
                pst.setString(4, emailText);
                pst.setString(5, contactText);
                pst.setString(6, roleText);
                pst.setString(7, usernameText);
                pst.setString(8, hashedPassword);
                pst.setInt(9, userId);

                pst.executeUpdate();
                pst.close();
            }

            conn.close();

            JOptionPane.showMessageDialog(this,
                    "User updated successfully!");

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Database error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_save_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_button;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField em;
    private javax.swing.JTextField firstname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField middlename;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel personal;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JLabel save_button;
    private javax.swing.JTextField user;
    private javax.swing.JLabel welcome10;
    private javax.swing.JLabel welcome11;
    private javax.swing.JLabel welcome12;
    private javax.swing.JLabel welcome14;
    private javax.swing.JLabel welcome15;
    private javax.swing.JLabel welcome16;
    private javax.swing.JLabel welcome2;
    private javax.swing.JLabel welcome6;
    private javax.swing.JLabel welcome7;
    private javax.swing.JLabel welcome8;
    private javax.swing.JLabel welcome9;
    // End of variables declaration//GEN-END:variables
}
