/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import Config.User;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class requestManage extends javax.swing.JFrame {

    /**
     * Creates new form requestManage
     */
    public requestManage() {
        initComponents();
        loadRequests();
    }
 private void openFrame(javax.swing.JFrame frame) {
                this.dispose();        // close current window
                frame.setVisible(true); // open new window
            }
 
    private void loadRequests() {
       DefaultTableModel model =
           (DefaultTableModel) requestsTable.getModel();
       model.setRowCount(0);

       try {
           config.connectDB db = new config.connectDB();
           java.sql.Connection conn = db.getConnection();

           String sql =
               "SELECT r.request_id, " +
               "res.first_name || ' ' || res.last_name AS resident_name, " +
               "d.document_name, r.purpose, r.status, " +
               "r.request_date, r.approved_at " +
               "FROM requests r " +
               "JOIN residents res ON r.resident_id = res.resident_id " +
               "JOIN documents d ON r.document_id = d.document_id " +
               "ORDER BY r.request_date DESC";

           java.sql.PreparedStatement pst = conn.prepareStatement(sql);
           java.sql.ResultSet rs = pst.executeQuery();

           while (rs.next()) {
               model.addRow(new Object[]{
                   rs.getInt("request_id"),
                   rs.getString("resident_name"),
                   rs.getString("document_name"),
                   rs.getString("purpose"),
                   rs.getString("status"),
                   rs.getString("request_date"),
                   rs.getString("approved_at")
               });
           }

           rs.close();
           pst.close();
           conn.close();

       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
   }
    
    private void approveRequest() {

    int selectedRow = requestsTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Select a request first.");
        return;
    }

    int requestId = Integer.parseInt(
        requestsTable.getValueAt(selectedRow, 0).toString()
    );

    try {
        config.connectDB db = new config.connectDB();
        java.sql.Connection conn = db.getConnection();

        String sql =
            "UPDATE requests SET " +
            "status = 'Approved', " +
            "approved_by = ?, " +
            "approved_at = CURRENT_TIMESTAMP " +
            "WHERE request_id = ?";

        java.sql.PreparedStatement pst =
            conn.prepareStatement(sql);

        pst.setInt(1, Config.User.getInstance().getUserId());
        pst.setInt(2, requestId);

        pst.executeUpdate();

        pst.close();
        conn.close();

        loadRequests();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    private void rejectRequest() {

    int selectedRow = requestsTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Select a request first.");
        return;
    }

    int requestId = Integer.parseInt(
        requestsTable.getValueAt(selectedRow, 0).toString()
    );

    String remarks = JOptionPane.showInputDialog(
        this,
        "Enter rejection reason:");

    if (remarks == null || remarks.trim().isEmpty()) return;

    try {
        config.connectDB db = new config.connectDB();
        java.sql.Connection conn = db.getConnection();

        String sql =
            "UPDATE requests SET " +
            "status = 'Rejected', " +
            "approved_by = ?, " +
            "approved_at = CURRENT_TIMESTAMP, " +
            "remarks = ? " +
            "WHERE request_id = ?";

        java.sql.PreparedStatement pst =
            conn.prepareStatement(sql);

        pst.setInt(1, Config.User.getInstance().getUserId());
        pst.setString(2, remarks);
        pst.setInt(3, requestId);

        pst.executeUpdate();

        pst.close();
        conn.close();

        loadRequests();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
      Color hoverColor = new Color (255,0,51);
                Color navColor = new Color (255,102,51);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        welcome4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dashPanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        residentsPanel = new javax.swing.JPanel();
        residents = new javax.swing.JLabel();
        requestPanel = new javax.swing.JPanel();
        request = new javax.swing.JLabel();
        issuancePanel = new javax.swing.JPanel();
        issuance = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        users1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestsTable = new javax.swing.JTable();
        approve = new javax.swing.JButton();
        reject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        welcome4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome4.setText("B D R S");
        jPanel4.add(welcome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ChatGPT Image Feb 19, 2026, 10_44_19 PM (1).png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        dashPanel.setBackground(new java.awt.Color(255, 102, 51));
        dashPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashPanelMouseExited(evt);
            }
        });
        dashPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashPanel.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(dashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, -1));

        profilePanel.setBackground(new java.awt.Color(255, 102, 51));
        profilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilePanelMouseExited(evt);
            }
        });
        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profilePanel.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(profilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, -1));

        residentsPanel.setBackground(new java.awt.Color(255, 102, 51));
        residentsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                residentsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                residentsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                residentsPanelMouseExited(evt);
            }
        });
        residentsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        residents.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        residents.setForeground(new java.awt.Color(255, 255, 255));
        residents.setText("Manage Residents");
        residentsPanel.add(residents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 40));

        jPanel2.add(residentsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 170, -1));

        requestPanel.setBackground(new java.awt.Color(255, 102, 51));
        requestPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                requestPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                requestPanelMouseExited(evt);
            }
        });
        requestPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        request.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        request.setForeground(new java.awt.Color(255, 255, 255));
        request.setText("Request");
        requestPanel.add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(requestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 170, -1));

        issuancePanel.setBackground(new java.awt.Color(255, 102, 51));
        issuancePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuancePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issuancePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issuancePanelMouseExited(evt);
            }
        });
        issuancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issuance.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        issuance.setForeground(new java.awt.Color(255, 255, 255));
        issuance.setText("Documents");
        issuancePanel.add(issuance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(issuancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 170, -1));

        logoutPanel.setBackground(new java.awt.Color(153, 51, 0));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelMouseExited(evt);
            }
        });
        logoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LOG OUT");
        logoutPanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 40));

        jPanel2.add(logoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 140, -1));

        userPanel.setBackground(new java.awt.Color(255, 102, 51));
        userPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userPanelMouseExited(evt);
            }
        });
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        users1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        users1.setForeground(new java.awt.Color(255, 255, 255));
        users1.setText("Manage Users");
        userPanel.add(users1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        jPanel2.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 610));

        jPanel5.setBackground(new java.awt.Color(255, 102, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Requests");
        jPanel5.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 730, 50));

        requestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Resident", "Document", "Purpose", "Status"
            }
        ));
        jScrollPane2.setViewportView(requestsTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 700, 360));

        approve.setText("Approve");
        approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveActionPerformed(evt);
            }
        });
        jPanel1.add(approve, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 90, -1));

        reject.setText("Reject");
        reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectActionPerformed(evt);
            }
        });
        jPanel1.add(reject, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPanelMouseClicked
        openFrame(new adminDashboard());
    }//GEN-LAST:event_dashPanelMouseClicked

    private void dashPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPanelMouseEntered
        dashPanel.setBackground(hoverColor);
    }//GEN-LAST:event_dashPanelMouseEntered

    private void dashPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPanelMouseExited
        dashPanel.setBackground(navColor);
    }//GEN-LAST:event_dashPanelMouseExited

    private void profilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseClicked

    }//GEN-LAST:event_profilePanelMouseClicked

    private void profilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseEntered
        profilePanel.setBackground(hoverColor);
    }//GEN-LAST:event_profilePanelMouseEntered

    private void profilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseExited
        profilePanel.setBackground(navColor);
    }//GEN-LAST:event_profilePanelMouseExited

    private void residentsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residentsPanelMouseClicked
        openFrame(new residentsManage());
    }//GEN-LAST:event_residentsPanelMouseClicked

    private void residentsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residentsPanelMouseEntered
        residentsPanel.setBackground(hoverColor);
    }//GEN-LAST:event_residentsPanelMouseEntered

    private void residentsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residentsPanelMouseExited
        residentsPanel.setBackground(navColor);
    }//GEN-LAST:event_residentsPanelMouseExited

    private void requestPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestPanelMouseClicked
        openFrame(new requestManage());
    }//GEN-LAST:event_requestPanelMouseClicked

    private void requestPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestPanelMouseEntered
        requestPanel.setBackground(hoverColor);
    }//GEN-LAST:event_requestPanelMouseEntered

    private void requestPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestPanelMouseExited
        requestPanel.setBackground(navColor);
    }//GEN-LAST:event_requestPanelMouseExited

    private void issuancePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuancePanelMouseClicked
        openFrame(new documentsManage());
    }//GEN-LAST:event_issuancePanelMouseClicked

    private void issuancePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuancePanelMouseEntered
        issuancePanel.setBackground(hoverColor);
    }//GEN-LAST:event_issuancePanelMouseEntered

    private void issuancePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuancePanelMouseExited
        issuancePanel.setBackground(navColor);
    }//GEN-LAST:event_issuancePanelMouseExited

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked

        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {
            User.getInstance().clearSession();
            new authentication.login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void logoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseEntered

    }//GEN-LAST:event_logoutPanelMouseEntered

    private void logoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseExited

    }//GEN-LAST:event_logoutPanelMouseExited

    private void userPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseClicked

    }//GEN-LAST:event_userPanelMouseClicked

    private void userPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseEntered
        openFrame(new userManage());
    }//GEN-LAST:event_userPanelMouseEntered

    private void userPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseExited
        openFrame(new userManage());
    }//GEN-LAST:event_userPanelMouseExited

    private void approveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveActionPerformed
      
    int selectedRow = requestsTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Select a request first.");
        return;
    }

    String currentStatus =
        requestsTable.getValueAt(selectedRow, 4).toString();

    if (!currentStatus.equalsIgnoreCase("Pending")) {
        JOptionPane.showMessageDialog(this,
            "This request is already processed.");
        return;
    }

    int requestId = Integer.parseInt(
        requestsTable.getValueAt(selectedRow, 0).toString()
    );

    try {
        config.connectDB db = new config.connectDB();
        java.sql.Connection conn = db.getConnection();

        String sql =
            "UPDATE requests SET " +
            "status = 'Approved', " +
            "approved_by = ?, " +
            "approved_at = CURRENT_TIMESTAMP " +
            "WHERE request_id = ?";

        java.sql.PreparedStatement pst =
            conn.prepareStatement(sql);

        pst.setInt(1, Config.User.getInstance().getUserId());
        pst.setInt(2, requestId);

        pst.executeUpdate();

        pst.close();
        conn.close();

        loadRequests();

        JOptionPane.showMessageDialog(this,
            "Request approved successfully!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_approveActionPerformed

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
   
    int selectedRow = requestsTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Select a request first.");
        return;
    }

    String currentStatus =
        requestsTable.getValueAt(selectedRow, 4).toString();

    if (!currentStatus.equalsIgnoreCase("Pending")) {
        JOptionPane.showMessageDialog(this,
            "This request is already processed.");
        return;
    }

    int requestId = Integer.parseInt(
        requestsTable.getValueAt(selectedRow, 0).toString()
    );

    String remarks = JOptionPane.showInputDialog(
        this,
        "Enter rejection reason:");

    if (remarks == null || remarks.trim().isEmpty()) return;

    try {
        config.connectDB db = new config.connectDB();
        java.sql.Connection conn = db.getConnection();

        String sql =
            "UPDATE requests SET " +
            "status = 'Rejected', " +
            "approved_by = ?, " +
            "approved_at = CURRENT_TIMESTAMP, " +
            "remarks = ? " +
            "WHERE request_id = ?";

        java.sql.PreparedStatement pst =
            conn.prepareStatement(sql);

        pst.setInt(1, Config.User.getInstance().getUserId());
        pst.setString(2, remarks);
        pst.setInt(3, requestId);

        pst.executeUpdate();

        pst.close();
        conn.close();

        loadRequests();

        JOptionPane.showMessageDialog(this,
            "Request rejected successfully!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_rejectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(requestManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(requestManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(requestManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(requestManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new requestManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approve;
    private javax.swing.JPanel dashPanel;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel issuance;
    private javax.swing.JPanel issuancePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton reject;
    private javax.swing.JLabel request;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JTable requestsTable;
    private javax.swing.JLabel residents;
    private javax.swing.JPanel residentsPanel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel users1;
    private javax.swing.JLabel welcome4;
    // End of variables declaration//GEN-END:variables
}
